### PR TITLE
fix(operator): remove `status` from crd.yml

### PR DESCRIPTION
**Pull request by misterkramer**
The CRD shouldn't include the status field as an input (it's an output field)

### CODE REVIEW

**Comment by misterkramer** [comment]
This is also controlled and generated from the operator-sdk. I have to look there.
Sorry for the wrong PR.

**Comment by misterkramer** [comment]
https://github.com/kubernetes-sigs/controller-tools/issues/456

**Comment by f41gh7** [comment]
i guess, its possible to patch and remove it after generation. Will take a look.

**Comment by misterkramer** [comment]
> i guess, its possible to patch and remove it after generation. Will take a look. 

Make an issue? Not to forget

In a good way it should fix here - https://github.com/kubernetes-sigs/controller-tools/issues/456

**Comment by f41gh7** [comment]
Must be fixed in master branch https://github.com/VictoriaMetrics/operator/tree/master/config/crd/bases

 Tomorrow i'm going to build new release and update helm-chart.

**Comment by f41gh7** [comment]
@misterkramer  must be fixed. I've subscribed  for controller-tools issue.

**Pull request closed without merging**
