### PR TITLE
[victoria-metrics-k8s-stack] Prometheus Operator CRDs (#341)

### PR DESCRIPTION
**Pull request by beliys**
Hi! Small patch for https://github.com/VictoriaMetrics/helm-charts/issues/341

### CODE REVIEW

**Comment by Haleygo** [comment]
I have one concern though, CRDs in prometheus-operator-crds are under `/crds/templates`, so they are treated as regular templates and will be managed by Helm. That means prometheus CRDs also will be deleted when uninstall VM release[with prometheus-operator-crds.enabled], and it could break all the prometheus CR resources user has, which is not good for VM-k8s-stack IMO.

**Comment by beliys** [comment]
@Haleygo Yes, but this is an optional feature. It is always possible to make prometheus-operator-crds independent, it sets prometheus-operator-crds.enabled=false and sets prometheus-operator-crds as a separate chart.
But I think there will not be many such users. Most users of victoria-metrics-k8s-stack appreciate being able to set everything with one chart.

**Comment by Haleygo** [comment]
>Most users of victoria-metrics-k8s-stack appreciate being able to set everything with one chart.

Thanks, I'm ok with the default value `prometheus-operator-crds.enabled=false`.
Do you have second opinion? @zekker6 @f41gh7 @Amper

**Review by zekker6 — APPROVED** [review]
LGTM

**Review by f41gh7 — APPROVED** [review]
LGTM

**Pull request merged**
