### PR TITLE
vmstack: dashboards and rules upgrade, added minikube setup instructions

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
upgraded dashboards and rules, added instructions about how to set up vmstack in minikube

### CODE REVIEW

**Review by Haleygo — APPROVED** [review]
LGTM

**Review by dmitryk-dk — DISMISSED** [review]
LGTM! Checked on local minikube installation

**Comment by zekker6** [comment]
@AndrewChubatiuk Could you add a changelog entry to mention dashboards and rules update?

**Review by zekker6 — APPROVED** [review]

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Comment by f41gh7** [comment]
Thanks for contribution!

**Pull request merged**
