### PR TITLE
Add ports for all ingestion protocols to vmagent

### PR DESCRIPTION
**Pull request by sti-jans**
Added the ability to add ports for all ingestion protocols in vmagent

### CODE REVIEW

**Comment by f41gh7** [comment]
It looks good to me and should work.

 But probably its better to introduce additional config option:

smthg like:
```yaml
insertPorts:
 graphite: 
   enabled: false
   port: 1112
 influx:
   enabled: false
   port: 1113
 openTSDB:
  enabled: false
  port: 1114
```
 And add it explicitly? 
 It will be documented and more obvious.

 What do you think?

**Comment by sti-jans** [comment]
I agree.
The current implementation was made by analogy with other charts.
In the args section, it is better to set these values before `.Values.extraArgs` ?

**Comment by f41gh7** [comment]
Can you add example of usage to the chart readme and  lets merge it as is.

**Comment by f41gh7** [comment]
Thanks for contribution!

**Pull request merged**
