### PR TITLE
Split templates of resources per kind - fix helm linting. (fix #819).

### LINKED ISSUE #819: [victoria-metrics-k8s-stack] Fail helm linting if ingresses enabled
Fail helm linting if ingresses enabled

Reproduce:
```bash
# helm version
version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.20.11"}
# helm repo add vm https://victoriametrics.github.io/helm-charts/
"vm" has been added to your repositories
# helm pull vm/victoria-metrics-k8s-stack --untar --version=0.18.11
# helm lint victoria-metrics-k8s-stack
==> Linting victoria-metrics-k8s-stack

1 chart(s) linted, 0 chart(s) failed
# helm lint victoria-metrics-k8s-stack --set vmagent.ingress.enabled=true
==> Linting victoria-metrics-k8s-stack
[ERROR] templates/victoria-metrics-operator/vmagent.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: networking.k8s.io/v1

Error: 1 chart(s) linted, 1 chart(s) failed
# helm lint victoria-metrics-k8s-stack --set vmalert.ingress.enabled=true
==> Linting victoria-metrics-k8s-stack
[ERROR] templates/victoria-metrics-operator/vmalert/vmalert.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: networking.k8s.io/v1

Error: 1 chart(s) linted, 1 chart(s) failed
# helm lint victoria-metrics-k8s-stack --set vmsingle.ingress.enabled=true
==> Linting victoria-metrics-k8s-stack
[ERROR] templates/victoria-metrics-operator/vmsingle.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: networking.k8s.io/v1

Error: 1 chart(s) linted, 1 chart(s) failed
# helm lint victoria-metrics-k8s-stack --set vmcluster.ingress.select.enabled=true,vmcluster.enabled=true
==> Linting victoria-metrics-k8s-stack
[ERROR] templates/victoria-metrics-operator/vmcluster.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: networking.k8s.io/v1

Error: 1 chart(s) linted, 1 chart(s) failed
# helm lint victoria-metrics-k8s-stack --set vmcluster.ingress.storage.enabled=true,vmcluster.enabled=true
==> Linting victoria-metrics-k8s-stack
[ERROR] templates/victoria-metrics-operator/vmcluster.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: networking.k8s.io/v1

Error: 1 chart(s) linted, 1 chart(s) failed
# helm lint victoria-metrics-k8s-stack --set vmcluster.ingress.insert.enabled=true,vmcluster.enabled=true
==> Linting victoria-metrics-k8s-stack
[ERROR] templates/victoria-metrics-operator/vmcluster.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: networking.k8s.io/v1

Error: 1 chart(s) linted, 1 chart(s) failed
```

### PR DESCRIPTION
**Pull request by MemberIT**
Fix issue #819

### CODE REVIEW

**Review by Haleygo — APPROVED** [review]
Thanks for the fix!
Could you also help adding the fix description to [changelog](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/CHANGELOG.md#L5)? Something like
> - Fix `helm lint` when ingress resources enabled. (#820)

**Comment by MemberIT** [comment]
@Haleygo 
CHANGELOG updated

**Comment by Haleygo** [comment]
> @Haleygo CHANGELOG updated

Thanks, but little mistake here, that should be under [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/CHANGELOG.md#L5):)

**Comment by MemberIT** [comment]
Oh, excuse me. Fixed it.

**Review by Haleygo — APPROVED** [review]
lgtm

**Pull request merged**
