### PR TITLE
openshift_compatibility

### PR DESCRIPTION
**Pull request by Baboulinet-33**
Hello,

I wanted to use victoria logs on openshift but openshift don't like fixed securityContext ("fsGroup" "runAsUser" "runAsGroup").
So I've make some modification on chart to be compatible with openshift.

The modification are clearly a copy/paste of bitnami solution (https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_compatibility.tpl) - you can keep the modification on `_helpers.tpl` or add the following dependency on all charts:
```yaml
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
```

For all securityContext parameter, you have a property `enabled` to enable this parameter.
And you have the parameter  `global.compatibility.openshift.adaptSecurityContext ` with value `auto`, `force`, `disabled`:
- auto: apply if the detected running cluster is Openshift
- force: perform the adaptation always
- disabled: do not perform adaptation

An example with auto:
```yaml
spec:
      containers:
        - name: victoria-logs-single-server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          image: "victoriametrics/victoria-logs:v0.5.2-victorialogs"
          [...]
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 60
      volumes:
        - name: server-volume
          emptyDir: {}
```

With force:
**openshift: force**
```yaml
spec:
      containers:
        - name: victoria-logs-single-server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          image: "victoriametrics/victoria-logs:v0.5.2-victorialogs"
          [...]
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: server-volume
          emptyDir: {}
```

### CODE REVIEW

**Comment by Baboulinet-33** [comment]
Hi, I forgot to respond but I addressed the points mentionned

**Review by Haleygo — APPROVED** [review]
LGTM

**Comment by Haleygo** [comment]
Thanks for contribution!

**Comment by TheMeier** [comment]
just a remark for some future similar changes. maybe it is a good idea to introduce new toggles with defaults set so they match the previous behaviour. 
IMHO the default for `server.podSecurityContext.enabled` should have been `true`

**Comment by Haleygo** [comment]
> just a remark for some future similar changes. maybe it is a good idea to introduce new toggles with defaults set so they match the previous behaviour. IMHO the default for `server.podSecurityContext.enabled` should have been `true`

@TheMeier Yes, thank you for notice and sorry for inconvenience!
It shouldn't break any previous customized securityContext, please see https://github.com/VictoriaMetrics/helm-charts/pull/1023.

**Pull request merged**
