### PR TITLE
fix: imagePullSecrets was in the wrong place in the default values file

### PR DESCRIPTION
**Pull request by StuxxNet**
Hello, guys!

Pretty simple fix. Found this while I was trying out the chart! 

Seems like the placement of the imagePullSecrets for the server configuration is wrong in the default values file.

Best Regards,
Ramon Borges

### CODE REVIEW

**Review by Haleygo — APPROVED** [review]
LGTM!

**Comment by Haleygo** [comment]
Thanks for contribution!

**Comment by tenmozes** [comment]
@Haleygo could you please update changelog as well

**Comment by Haleygo** [comment]
> @Haleygo could you please update changelog as well

Yeah, on the way.

**Pull request merged**
