### PR TITLE
Enable latest etcd dashboard, use jsonnet mixin

### PR DESCRIPTION
**Pull request by kvaster**
Update etcd rules to latest, add etcd dashboard using latest source - jsonnext mixin.

### CODE REVIEW

**Comment by kvaster** [comment]
Also have one question: why [k8s-views-nodes.json](https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/k8s-views-nodes.json) and [k8s-system-api-server.json](https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/k8s-system-api-server.json) were excluded ? Is there any reason for this ?

**Comment by ksa-real** [comment]
nit: jsonnext -> jsonnet

**Comment by kvaster** [comment]
Any comments ?

**Comment by tenmozes** [comment]
@Haleygo @Amper @f41gh7 any updates?

**Comment by Haleygo** [comment]
@k1rk Could you help with this one?

**Comment by tenmozes** [comment]
@k1rk ping

**Review by Haleygo — DISMISSED** [review]
LGTM!

**Comment by Haleygo** [comment]
Thank you! @kvaster  @AndrewChubatiuk

**Comment by AndrewChubatiuk** [comment]
I've just rebased it, but it's not working, as jsonnet expects all libraries to be present locally, while script only downloads mixin.libsonnet file

**Review by AndrewChubatiuk — CHANGES_REQUESTED** [review]
I've just rebased it, but it's not working, as jsonnet expects all mixin libraries to be present locally, while script only downloads mixin.libsonnet file.
@kvaster if you can manage somehow make it working, could you please run it and commit generated rules and dashboards?

**Comment by AndrewChubatiuk** [comment]
closing this PR in a favour of #1209

**Comment by kvaster** [comment]
I already have the updated version. If you need. I was waiting for this more than a year and now it is closed...

**Comment by AndrewChubatiuk** [comment]
hey @kvaster this features will be introduces after #1209 is merged, thanks for your help

**Comment by kvaster** [comment]
No problem. If you wish to reimplement it again - no problem. Personally I'm discouraged to make any new contributions to this project. Everyone was silent for more than a year and after my PR was closed.

**Comment by AndrewChubatiuk** [comment]
Sorry to hear that, but you could at least leave reaction to a [message](https://github.com/VictoriaMetrics/helm-charts/pull/509#pullrequestreview-2215806091), which was posted a week ago for us to understand, that you're still interested in this.

**Comment by kvaster** [comment]
This was the only one week in a year I was on a trip and without possibility to answer fast :) Anyway thanks for fixing this at last, cause it was very annoying to constantly rebase the patch.

**Comment by Haleygo** [comment]
@kvaster 
Sorry for the bad experience!
As an open-source project, we welcome contributions and strive to be positive about them. However, maintainers sometimes lack the knowledge to accept pull requests and may hesitate to merge them. Luckily, @AndrewChubatiuk recently joined us and he's an expert in CICD. 
Hope you enjoy our charts more in the future!

**Comment by kvaster** [comment]
Thanks. Let's do our best for the opensource world. Don't want to make this a 'bad' conversation. So I want to thanks one more again - we're using the chart and now it will be much more easier to maintain it. I will make some small PR's very soon - changes we're using at our place right now.

p.s.: no response at all is much worse then lack of knowledge. And again thanks.

**Pull request closed without merging**
