### PR TITLE
operator: generate webhook certs without cert-manager, enable webhook by default

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks!

**Comment by farcaller** [comment]
This broke the cert-manager setup, because the webhook options ended in Issuer/victoria-metrics-operator-root. Can you please make sure this renders properly for `admissionWebhooks.certManager.enabled = true`?

**Comment by farcaller** [comment]
I think it's the incorrect resource split; the suggested fix is in https://github.com/VictoriaMetrics/helm-charts/pull/1315.

Isn't helm fun?

**Pull request merged**
