### PR TITLE
Fix relabelConfigs for operator scrape

### PR DESCRIPTION
**Pull request by timp87**
Fix [option name](https://docs.victoriametrics.com/operator/api.html#endpoint) for victoria-metrics-operator VMServiceScrape

### CODE REVIEW

**Comment by Haleygo** [comment]
Good catch, thanks!
Do you mind to fix the other places where misconfigured `relabelings` as well?
https://github.com/search?q=repo%3AVictoriaMetrics%2Fhelm-charts+relabelings+%7D%7D+++++++relabelings%3A&type=code

**Comment by timp87** [comment]
@Haleygo  done

**Comment by Haleygo** [comment]
@timp87 Sorry for misleading, turns out prometheus [servicemonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Endpoint) uses `relabelings` instead of `relabelConfigs`.
Your first commit was totally right, could you plz revert it?

**Comment by timp87** [comment]
@Haleygo done again ;)

**Review by Haleygo — APPROVED** [review]
LGTM!
Thank you!

**Pull request merged**
