### PR TITLE
Argocd synchronization annotations

### PR DESCRIPTION
**Pull request by bkomraz1**
[Feature][operator] Argocd synchronization annotation

https://github.com/VictoriaMetrics/helm-charts/issues/370

Signed-off-by: Boris Komraz <bkomraz1@gmail.com>

### CODE REVIEW

**Comment by tenmozes** [comment]
@k1rk, @f41gh7  could you please review?

**Comment by k1rk** [comment]
@bkomraz1 thanks for contribution
i replied in original issue, basically this can be achieved without any changes in chart

**Review by f41gh7 — DISMISSED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks for contribution!

**Pull request merged**
