### PR TITLE
Add PVC for deployment mode

### LINKED ISSUE #27: Victoria-metrics-single deployment mode doesn't create PVC
It has a default for the name of the PVC if an existing one isn't defined, but it doesn't create that PVC.

### PR DESCRIPTION
**Pull request by tanelso2**
Fixes #27 

Tested with: helm install --dry-run --debug

### CODE REVIEW

**Comment by tenmozes** [comment]
looks good to me, thanks

**Comment by tenmozes** [comment]
i will create release soon

**Comment by tanelso2** [comment]
Thanks!

**Comment by tanelso2** [comment]
@tenmozes - can you notify me when a version of the chart with this change is released please?

**Comment by tenmozes** [comment]
Already done

**Comment by tanelso2** [comment]
I'm only seeing a v0.2.1 in the helm repo at the moment, which doesn't include this change

**Comment by tenmozes** [comment]
please try again 0.3.0 version should appear

**Comment by tanelso2** [comment]
I've got it now. Thank you!

**Pull request merged**
