### PR TITLE
Added spec params description

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
related issues #1244 #255
- expose spec urls in params description
- render param object in REAMDE as yaml

### CODE REVIEW

**Review by Haleygo — COMMENTED** [review]
hmm, I'm not sure about using HTML tags, they make README better but the values.yaml is a bit messy.

**Comment by AndrewChubatiuk** [comment]
I would also like to keep markdown tables instead of html ones, but multiline content breaks markdown tables and markdown is not rendered inside html. I can add to hugo-docs a PR, which adds function, which allow markdown to html conversion

**Comment by AndrewChubatiuk** [comment]
removed HTML tags from values and and rendered documentation by helm-docs binary from [this](https://github.com/norwoodj/helm-docs/pull/262) PR

**Comment by AndrewChubatiuk** [comment]
@Haleygo
Since there's no activity in helm-docs repo for a month, so I've built a docker image with my fork
could you please review it again?

**Comment by Haleygo** [comment]
> `#` -- Extra Volume Mounts for the container
  extraVolumeMounts:
    []
    # - name: example
    #   mountPath: /example

A minor question: is there a way to support value's comment without adding the prefix `# --`? 
I'm just concerned that I or other contributors might forget to add this for new values in the future.

**Review by Haleygo — APPROVED** [review]
LGTM

**Pull request merged**
