### PR TITLE
operator: improved rendering speed

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
- operator and k8s-stack: improved operator rendering speed
- k8s-stack: fixed case, when license is not set at all
- k8s-stack: fixed  templates for case, when `<service>.name` is set

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by vadym-replianchuk** [comment]
I ran into a problem while trying to install the **victoria-metrics-k8s-stack** version 0.25.6 chart via FluxCD (v2.3.0).

Here are the error:
```
Helm upgrade failed for release monitoring/victoria-metrics with chart victoria-metrics-k8s-stack@0.25.6: template:
victoria-metrics-k8s-stack/templates/rules/additionalVictoriaMetricsRules.yml:19:17: executing "victoria-metrics-k8s-stack/templates/rules/additionalVictoriaMetricsRules.yml" at <include "victoria-metrics-k8s-stack.labels" $ctx>:
error calling include: template: victoria-metrics-k8s-stack/templates/_helpers.tpl:58:28: executing "victoria-metrics-k8s-stack.labels" at <include "victoria-metrics-k8s-stack.selectorLabels" .>:
error calling include: template: victoria-metrics-k8s-stack/templates/_helpers.tpl:76:50: executing "victoria-metrics-k8s-stack.selectorLabels" at <include "victoria-metrics-k8s-stack.name" .>:
error calling include: template: victoria-metrics-k8s-stack/templates/_helpers.tpl:5:55: executing "victoria-metrics-k8s-stack.name" at <63>: invalid value; expected string
```

Can you help please?

**Comment by AndrewChubatiuk** [comment]
@vadym-replianchuk fix is available in 0.25.7

**Comment by vadym-replianchuk** [comment]
Thank you!

**Comment by tjwallace** [comment]
With this change, when the `fullnameOverride` value is set (to `victoria-metrics` in my case) the ingress `vmalert-victoria-metrics` is now named `victoria-metrics` and it references a service that does not exist `victoria-metrics:8080`. Any idea why it lost the `vmalert` prefix?

**Comment by AndrewChubatiuk** [comment]
hey @tjwallace
sorry for inconvenience, it's a bug, will be available in a new release

**Comment by AndrewChubatiuk** [comment]
fix release in 0.25.9

**Comment by dhess** [comment]
This change (or perhaps #1357) broke `victoria-metrics-k8s-stack` with `vmagent.enabled: true` and `externalVM.write.url`:

```
VMAgent.operator.victoriametrics.com "victoria-metrics" is invalid: spec.remoteWrite[0].url: Required value
```

**Comment by AndrewChubatiuk** [comment]
@dhess fix is expected to be in 0.25.10 soon

**Comment by AndrewChubatiuk** [comment]
it's already available

**Comment by dhess** [comment]
@AndrewChubatiuk That seems to have done the trick, thank you!

**Pull request merged**
