### PR TITLE
Remove invalid `scheme` for `tcpSocket` `livenessProbe`s

### PR DESCRIPTION
**Pull request by MisguidedEmails**
The chart currently fails to deploy for me due to this error.

See - https://github.com/VictoriaMetrics/helm-charts/issues/843

### CODE REVIEW

**Review by Haleygo — APPROVED** [review]
LGTM!

**Comment by Haleygo** [comment]
Thanks for the fix!

**Comment by AutonomicMattRoy** [comment]
will this be released for `0.11.x` charts? It looks like `0.11.11` still has this issue present and there is no `0.11.12` available for cluster

**Comment by Haleygo** [comment]
> will this be released for `0.11.x` charts? It looks like `0.11.11` still has this issue present and there is no `0.11.12` available for cluster

@AutonomicMattRoy Indeed, we will build `0.11.12` after [this https://github.com/VictoriaMetrics/helm-charts/pull/844](https://github.com/VictoriaMetrics/helm-charts/pull/845)

**Pull request merged**
