### PR TITLE
fix typo in suppressStorageFQDNsRender, address #580

### PR DESCRIPTION
**Pull request by tenmozes**

### CODE REVIEW

**Review by zekker6 — APPROVED** [review]

**Comment by f41gh7** [comment]
It breaks backward compatibility,  I suggest to define this variable at _helpers and set it from both variants.

**Comment by tenmozes** [comment]
@f41gh7 it doesn't break backward compatibility, please check the "check" in if statement

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks!

**Pull request merged**
