### PR TITLE
charts: add ability to provide extraObjects

### PR DESCRIPTION
**Pull request by zekker6**
Sync supported options between different charts to make sure all charts support extraObjects.

### CODE REVIEW

**Review by tenmozes — CHANGES_REQUESTED** [review]
Please update the changelog

**Review by f41gh7 — DISMISSED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks!

**Comment by zekker6** [comment]
@f41gh7 @Amper can we publish a release with those changes?
It blocks me a bit, so it would be great to have this released.

**Comment by Amper** [comment]
@zekker6 done

**Pull request merged**
