### PR TITLE
Patch 1

### LINKED ISSUE #287: [victoria-metrics-single] upgrade to 0.8.18 fails with "executing victoria-metrics-single/templates/server-service.yaml at <.Values.service.healthCheckNodePort>: nil pointer evaluating interface {}.healthCheckNodePort"
When upgrading the `victoria-metrics-single` chart to `0.8.18` the following error is reported:

```
Helm upgrade failed: template: victoria-metrics-single/templates/server-service.yaml:82:18: executing "victoria-metrics-single/templates/server-service.yaml" at <.Values.service.healthCheckNodePort>: nil pointer evaluating interface {}.healthCheckNodePort
```

I believe this is due to a missing  `server` key  [here in the server-service.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/27872131f84386cf43bd0f2a6ae22d710fb897fb/charts/victoria-metrics-single/templates/server-service.yaml#L82).

### PR DESCRIPTION
**Pull request by Jeinhaus**
This should fix #287

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks!

**Comment by Jeinhaus** [comment]
@f41gh7 What is the process for bumping the Chart's version? Should I have bumped it here or is there a separate build step that does it?

**Comment by f41gh7** [comment]
> @f41gh7 What is the process for bumping the Chart's version? Should I have bumped it here or is there a separate build step that does it?

 It's manual release, someone with write permissions have to package charts and push it to the corresponding branches.

**Pull request merged**
