### PR TITLE
victoria-metrics-cluster: Port name fix for custom port name in readiness and liveness check

### PR DESCRIPTION
**Pull request by hanumanhuda**
fixing https://github.com/VictoriaMetrics/helm-charts/issues/1060

### CODE REVIEW

**Comment by Haleygo** [comment]
Thank you for the fix!
Would you mind adding a line to the [changelog](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/CHANGELOG.md)?

**Review by Haleygo — DISMISSED** [review]

**Comment by hanumanhuda** [comment]
> Thank you for the fix! Would you mind adding a line to the [changelog](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/CHANGELOG.md)?

added entry in changelog.

**Review by zekker6 — APPROVED** [review]

**Comment by hanumanhuda** [comment]
@Haleygo / @zekker6 Could you help to merge this? I am seeing failure on the check.

**Comment by zekker6** [comment]
@hanumanhuda Thank you for your contribution!

**Comment by hanumanhuda** [comment]
by when we would have new version of victoria-metrics-cluster?

**Comment by Haleygo** [comment]
> by when we would have new version of victoria-metrics-cluster?

Will make releases after https://github.com/VictoriaMetrics/helm-charts/pull/1048, so most likely later today.

**Pull request merged**
